### ISSUE TITLE
Trouble getting plugin installed

### ISSUE THREAD

**Issue by Louis345** [JoaoCnh/react-native-android-voice#16]
I have made all the necessary changes in the instructions section.
After making the changes, I am unable to get my project to compile.

The error I am receiving is:
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':VoiceModule'.
  
  > failed to find Build Tools revision 23.0.2
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.168 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

I would appreciate any help.

**Comment by niftytushar** [comment]
Also facing same problem.

@Louis345 were you able to solve it?

**Comment by Louis345** [comment]
I was never able to solve this issue.  I followed the instructions and still had that issue.

**Comment by niftytushar** [comment]
Ok, I just solved the issue by installing Build Tools v23.0.2.

I had to make some changes to MainActivity.java also, it looks like this now:

```java
package com.foo;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.wmjmc.reactspeech.VoicePackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "foo";
    }

    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new VoicePackage());
    }
}
`

**Comment by niftytushar** [comment]
But now I ran into another issue. After importing SpeechAndroid is null.

**Comment by JoaoCnh** [comment]
I've just published v0.5.0. Please check if issues still persist for any of you and please feel free to report new ones.

Many thanks to everyone who contributed for v0.5.0 with PRs

**Comment by sumanbogati** [comment]
Hi,

I am trying to install this plugin into window7 but could not get the success, found following error:- 

![image](https://cloud.githubusercontent.com/assets/1753974/23833059/5e9b7ac6-0766-11e7-89ca-310d9fcde148.png)

My react-native configuration is

react-native-cli: 2.0.1
react-native: 0.41.2

**Comment by JoaoCnh** [comment]
@sumanbogati Can you please say which version of this package you're running?

I'm gonna try and make a table of compatibility of versions between this package and RN. I've been away for a while from RN so the versions are a bit unknown to me still. 

If you're running v0.5.0 try a previous version like v0.4.0 because it might me related to RN -> package compatibility
