### ISSUE TITLE
Update version to 0.4.0 in npm registery

### ISSUE THREAD

**Issue by jaggs6** [JoaoCnh/react-native-android-voice#18]
@JoaoCnh Please update the version in package.json and upload it to npm registery

**Comment by JoaoCnh** [comment]
gonna take care of this as soon as I can

**Comment by JoaoCnh** [comment]
I've just published v0.5.0. Please check if issues still persist for any of you and please feel free to report new ones.

Many thanks to everyone who contributed for v0.5.0 with PRs
