### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Noitidart** [JoaoCnh/react-native-android-voice#27]
Hi there,
I'm trying to use your awesome module. I followed the instructions in your readme but on build I am getting this:

FAILURE: Build failed with an exception.

```
* What went wrong:
A problem occurred configuring project ':VoiceModule'.
> Could not resolve all dependencies for configuration ':VoiceModule:classpath'.
   > Could not download transform-api.jar (com.android.tools.build:transform-api:1.5.0)
      > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/transform
-api/1.5.0/transform-api-1.5.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/transform-api/1
.5.0/transform-api-1.5.0.jar'. Received status code 500 from server: Internal Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
 more log output.

BUILD FAILED

Total time: 6 mins 33.853 secs
```

Do you have any ideas?

Thanks

**Comment by JoaoCnh** [comment]
@Noitidart Hey thanks for showing interest in this module. I'll have a look and try and figure out what is happening

**Comment by Noitidart** [comment]
Thank you very much @JoaoCnh ! :)

**Comment by JoaoCnh** [comment]
@Noitidart I tried investigating a bit. Can't really test on my machine right now. But it might be some maven repo problems. Have you tried again?

**Comment by Noitidart** [comment]
I will try again this week with a screencast. For now I have adopted IBM's Bluemix API - Watson, so it is cross platform :)

Thank you so much for following up with me! :)

**Comment by JoaoCnh** [comment]
@Noitidart np. any news update pls. I will close this issue for now.

**Comment by Noitidart** [comment]
Forgive me my man I got so busy, I will for sure updated this topic when I test it. I was having lots of success with Watson so was going with that for now. It was cross platform too so it had that bonus.
