### ISSUE TITLE
Error buil app

### ISSUE THREAD

**Issue by output4** [JoaoCnh/react-native-android-voice#28]
A problem occurred evaluating project ':VoiceModule'.
> Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.

"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-native-android-voice": "^0.5.1"
============================
Gradle 3.3
------------------------------------------------------------

Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.8.0-52-generic amd64

**Comment by JoaoCnh** [comment]
@nytuh I think this has to do with the Gradle version. I will take a look at this

**Comment by output4** [comment]
MayBe. I'm remove clean task in the you gradle config and app is builded normally. But now, your component, answer "E_SERVER_ERROR" before i speech.

**Comment by JoaoCnh** [comment]
@nytuh 

> E_SERVER_ERROR
> 
> SpeechAndroid.E_SERVER_ERROR
> Google's Servers encountered an error while processing the request

I have this in the docs. You must be connected to the internet.

**Comment by JoaoCnh** [comment]
@nytuh Closing since the problem could have been resolved. If the problem still remains please feel free to re-open
