### ISSUE TITLE
Project doesn't build with react-native 0.47.2

### ISSUE THREAD

**Issue by migzai** [JoaoCnh/react-native-android-voice#31]
Reason: react-native breaking change:
- ReactPackage removes the createJSModules method

**Comment by JoaoCnh** [comment]
@migzai Today will be merged a pull-request that addresses this issue and a new version will be released

**Comment by migzai** [comment]
Ok thanks.  Awaiting new release..

**Comment by JoaoCnh** [comment]
@migzai version 0.6.0 should now be available on npm
