### ISSUE TITLE
Voice Recognition without Toasts

### ISSUE THREAD

**Issue by hexicle** [JoaoCnh/react-native-android-voice#32]
Is it possible to do voice recognition without displaying any Toasts or Dialogs?
Because I have to call `startSpeech(prompt, locale)` to initialize voice recognition which I take to mean that there is no option to call startSpeech with no prompt.
Maybe there's something I'm missing here... I do not want any Toasts, Dialogs or prompts unless it's just the 'ok google' sound.

**Comment by JoaoCnh** [comment]
This uses the Android Native Speech Recognizer. It will always open the microphone dialog.

**Comment by hexicle** [comment]
Thank you that resolves my question.
