### ISSUE TITLE
Android Voice Modal

### ISSUE THREAD

**Issue by wenkesj** [JoaoCnh/react-native-android-voice#8]
Is there a way to remove the modal from popping up?

My application would serve a better purpose if the user had direct control over the speech button and display, do you know if that is possible?

**Comment by wenkesj** [comment]
@JoaoCnh https://github.com/wenkesj/react-native-android-voice let me know what you think. Updated the readme to explain the changes.

**Comment by JoaoCnh** [comment]
Hey @wenkesj 

First with the current RecognizerIntent Native from Android I don't think there is the ability to control that with their native options.

But there is a way in Android to use offline voice recognition and to control with events and callbacks. I have a milestone for it but I haven't been able to do much.

**Comment by de-code** [comment]
I came across that as well as I wasn't quite fond of the modal either.

You can use the [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer.html) to achieve that.

I wasn't sure whether it belonged into your module as it would be quite different, although it would use the same intent for the configuration. I also wanted to have a bit more freedom with the configuration. So for now I created https://github.com/de-code/react-native-android-speech-recognizer (and https://github.com/de-code/react-native-web-speech-api).

But you may want to include it in your module as a flag or separate method. Note though that all of the SpeechRecognizer methods need to be called from the main thread.

**EDIT**: Just noticed that you (@wenkesj) created https://github.com/wenkesj/react-native-voice
Not sure why I missed that.

**Comment by wenkesj** [comment]
@de-code I really like your style. I would love to see your code/repository get more popularity since I don't really work with mine anymore. That is well done and I think the API is more standardized then mine... Or maybe you can just take mine over lol. Either route you choose, I really appreciated the feedback

**Comment by de-code** [comment]
@wenkesj Thank you. Actually I thought your API was pretty good and sufficient for most use-cases. Your API lends itself for abstraction. I kind of went both extremes. Very Android specific which has the advantage of having access to the full power (like getting the multiple predictions with their confidence). The web API on the other hand is standard but a bit limited (it's not much code though). Probably good to offer them side by side but I was considering adding a project comparison somewhere. Happy to collaborate. (Once it's feature complete with a well defined scope I wouldn't expect there to be much need for active development.)
